on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          run: |
            az login --service-principal -u 18a2997c-cdfa-4eac-8d64-becbc7a4fef1 -p ZodIN5u_S.awwqu_d4uSErxNyU6c7BuWz~ --tenant ad888b01-5202-4130-908a-906b3dfdddc4
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build ./WebApplication -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/testapp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/testapp:${{ github.sha }}

        - uses: azure/webapps-deploy@v2
          with:
            app-name: 'testcicd1231'
            images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/testapp:${{ github.sha }}
    
        - name: Azure logout
          run: |
            az logout
