on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          run: |
            az login --service-principal -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} --tenant  ${{ secrets.AZURE_TENANT }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build ./WebApplication -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_REPOSITORY }}:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_REPOSITORY }}:${{ github.sha }}

        - uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ secrets.AZURE_DEPLOY_APP }}
            images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.AZURE_REPOSITORY }}:${{ github.sha }}
    
        - name: Azure logout
          run: |
            az logout
